import {
  Bell,
  Boxes,
  ChartLine,
  ClipboardList,
  Cog,
  Cpu,
  FileText,
  HeartPulse,
  Inbox,
  LayoutGrid,
  Lightbulb,
  ListChecks,
  ListTodo,
  ShieldCheck,
  Percent,
  Receipt,
  ScrollText,
  SlidersHorizontal,
  Speaker,
  TrendingUp,
  Users,
  Wallet,
  type LucideIcon,
} from 'lucide-react'

/** Icône de chaque entrée de navigation, par chemin (remplace les lettres de NAV_BY_PROFILE). */
export const NAV_ICONS: Record<string, LucideIcon> = {
  '/app/apercu': LayoutGrid,
  '/app/alertes': Bell,
  '/app/machines': Cog,
  '/app/equipements': Boxes,
  '/app/consommation': ChartLine,
  '/app/prediction': TrendingUp,
  '/app/conseils': Lightbulb,
  '/app/recommandations': ListChecks,
  '/app/factures': Receipt,
  '/app/facturation': Percent,
  '/app/rapports': FileText,
  '/app/plan-action': ListTodo,
  '/app/journal': ScrollText,
  '/app/audit': ShieldCheck,
  '/app/boitier': Speaker,
  '/app/admin/boitiers': Speaker,
  '/app/parametres': SlidersHorizontal,
  '/app/admin/sante': HeartPulse,
  '/app/admin/modeles': Cpu,
  '/app/admin/utilisateurs': Users,
  '/app/admin/leads': ClipboardList,
  '/app/admin/messages': Inbox,
  '/app/admin/facturation': Wallet,
}
